name: 'Release with Apache Maven'

description: Release with Apache Maven

inputs:
  github-token:
    description: 'Password or token for server authentication ; ex: secrets.GITHUB_TOKEN variable'
    required: true
  maven-version-next-snapshot-index-to-increment:
    description: 'Index of the version segment to increment for the next snapshot version (1-based). Default is 3 (patch version).'
    required: false
    default: '3'

runs:

  using: 'composite'

  steps:
    - uses: actions/checkout@v6

    - uses: actions/setup-java@v5
      with:
        distribution: 'temurin'
        java-version: '21'
        cache: 'maven'

    - run: echo "name=version::$(mvn help:evaluate -Dexpression='project.version' -q -DforceStdout)" >> $GITHUB_OUTPUT
      id: current-snapshot-version
      shell: bash

    - run: echo ${{ steps.current-snapshot-version.outputs.version }}
      shell: bash

    - run: mvn versions:set -DremoveSnapshot=true
      shell: bash

    - run: echo "name=version::$(mvn help:evaluate -Dexpression='project.version' -q -DforceStdout)" >> $GITHUB_OUTPUT
      id: tag-version
      shell: bash

    - run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add pom.xml
        git commit -m "Bump version from ${{ steps.current-snapshot-version.outputs.version }} to ${{ steps.tag-version.outputs.version }}"
        git push
      shell: bash

    - run: |
        TAG="${{ steps.tag-version.outputs.version }}"
        git tag $TAG
        git push origin $TAG
      shell: bash

    # https://docs.github.com/fr/actions/tutorials/publish-packages/publish-java-packages-with-maven#publication-de-packages-sur-github-packages
    - run: mvn --batch-mode deploy
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
      shell: bash

    - run: |
        TAG="${{ steps.tag-version.outputs.version }}"
        gh release create "$TAG" --title "$TAG" --notes "Release $TAG"
      env:
        GH_TOKEN: ${{ inputs.github-token }}
      shell: bash

    - run: mvn versions:set -DnextSnapshot=true -DnextSnapshotIndexToIncrement=${{ inputs.maven-version-next-snapshot-index-to-increment || '0' }}
      shell: bash

    - run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add pom.xml
        git commit -m "Prepare next development version"
        git push
      shell: bash
